### ISSUE TITLE
it isn't a known property of 'froala'

### ISSUE THREAD

**Issue by jlopez90** [Thrinacia/ng2-froala-editor#1]
Following your instructions:

Can't bind to 'froalaOptions' since it isn't a known property of 'froala'. ("<froala [ERROR ->][froalaOptions]="froalaOptions" [froalaData]="text" (model)="onFroalaModelChanged($event)" ...

What I'm missing?? Thanks so much

**Comment by ericleethrinacia** [comment]
Hello

I'm think it's probably for some reason not aware of the FroalaEditorModule / FroalaEditorComponent
Can you tell me which version is Angular2, Froala Editor, and also provide some sample code please
Also are you using webpack and systemjs

Thank you

**Comment by jlopez90** [comment]
Hi @ericleethrinacia 

I'm using Angular version 2.0.0, Froala editor version 1.0.13.

This is my.component.html:
<froala [froalaOptions]="froalaOptions" [froalaData]="text" (model)="onFroalaModelChanged($event)" (editorInitialized)="onEditorInitialized()"></froala>
 
----

import { Component, EventEmitter, Input, Output }        from '@angular/core';
import { FroalaEditorModule , FroalaEditorCompnoent} from 'ng2-froala-editor/ng2-froala-editor';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'my-editor',
    templateUrl: 'my-editor.component.html'
})
export class MyEditorComponent implements OnInit {

    text: string = '<div>Hey we are testing Froala Editor</div>';
    editor: any;

    @Input() froalaOptions: any; 
    @Input() froalaData: any; 

    constructor() {
        this.froalaOptions = {
            height: 300
        };
    }

    ngOnInit() { }

    onFroalaModelChanged(event: any) {
        setTimeout(() => {
            this.text = event;
        });
    }

    onEditorInitialized(event?: any) {
        // Save the editor instance
        this.editor = FroalaEditorCompnoent.getFroalaInstance();

        // Listen to Froala Editor's event
        this.editor.on('froalaEditor.focus', (e, editor) => {
            console.log("editor is focused");

            // Use Froala Editor's method
            this.editor.froalaEditor('codeView.toggle');
        });
    }

} 

--

I imported FroalaEditorModule from "ng2-froala-editor/ng2-froala-editor" in my main NgModule and I'm using Webpack because my project is based on angular-universal-starter.

Thanks!

**Comment by ericleethrinacia** [comment]
Hmm this is really weird
I assume you installed it through npm correct?
Do you maybe have a link to the project I can download and see if that's not too much trouble

Thank you!

**Comment by jlopez90** [comment]
Yes, I did through npm. It works OK on a Tour-of-Heroes Angular CLI project. My problem exists on a angular universal webpack config. Any idea? Thanks so much!

**Comment by jlopez90** [comment]
My mistake! I imported the FroalaEditorModule in the wrong module! It's working OK, good job!

**Comment by ericleethrinacia** [comment]
ah nice to hear it's solved!

**Comment by Achyuthkodali** [comment]
> My mistake! I imported the FroalaEditorModule in the wrong module! It's working OK, good job!

thank god.... Same issue for me and i solved it... Good day
