### ISSUE TITLE
AOT compile issue

### ISSUE THREAD

**Issue by RobertoNowak** [Thrinacia/ng2-froala-editor#4]
I found the error while i build app with AOT mode. ("ng build --prod --aot=true")
I think this module should be updated to be compatible with Angular 2.4.

**Comment by stardustxx** [comment]
Sorry for the super late reply
In the last 2 weeks, Angular 4 has been released so I updated the module to Angular 4
The AoT problem should be fixed now after I used ngc to compile
Sorry for the inconvenience, hope it works for you!
